#!/usr/bin/env node
"use strict";
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.resolve(__dirname, "..");
const CHECK = process.argv.includes("--check");
const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, "src/manifest.json"), "utf8"));
const changes = [];
const generatedContent = new Map();

function read(relative) { return fs.readFileSync(path.join(ROOT, relative), "utf8"); }
function expected(relative) { return generatedContent.get(relative) ?? read(relative); }
function emit(relative, content) {
  generatedContent.set(relative, content);
  const target = path.join(ROOT, relative);
  const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;
  if (current === content) return;
  changes.push(relative);
  if (!CHECK) { fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, content); }
}
function filesUnder(relative) {
  const base = path.join(ROOT, relative);
  if (!fs.existsSync(base)) return [];
  const output = [];
  for (const entry of fs.readdirSync(base, { withFileTypes: true })) {
    const child = path.posix.join(relative.replace(/\\/g,"/"), entry.name);
    if (entry.isDirectory()) output.push(...filesUnder(child)); else output.push(child);
  }
  return output;
}
function digest(relative) {
  const bytes = generatedContent.has(relative)
    ? Buffer.from(generatedContent.get(relative), "utf8")
    : fs.readFileSync(path.join(ROOT, relative));
  return { sha256: crypto.createHash("sha256").update(bytes).digest("hex"), bytes: bytes.length };
}

const capabilityContract = JSON.parse(read("src/contracts/extension-capabilities.json"));
const capabilities = capabilityContract.capabilities;
const capabilityIds = capabilities.map(item => item.id);
if (new Set(capabilityIds).size !== capabilityIds.length) throw new Error("Extension capability ids must be unique.");

const capabilityRuntimePath = "src/runtime/generated/05-extension-capability-contract.js";
const capabilityRuntime = `    /* Generated by scripts/build-release.js from src/contracts/extension-capabilities.json */\n` +
  `    const EXTENSION_CAPABILITY_DEFINITIONS = Object.freeze(${JSON.stringify(capabilities)}.map(Object.freeze));\n` +
  `    const EXTENSION_CAPABILITIES = Object.freeze(EXTENSION_CAPABILITY_DEFINITIONS.map(item => item.id));\n` +
  `    const EXTENSION_PERMISSIONS = new Set(EXTENSION_CAPABILITIES);\n\n`;
emit(capabilityRuntimePath, capabilityRuntime);

const capabilityRows = capabilities.map(item => `| \`${item.id}\` | ${item.risk} | ${item.description} |`).join("\n");
emit("EXTENSION_CAPABILITIES.md", `# Hybrid Tile Studio extension capabilities\n\n` +
  `Generated from \`src/contracts/extension-capabilities.json\`. Edit the contract, not this file.\n\n` +
  `| Capability | Risk | Purpose |\n|---|---|---|\n${capabilityRows}\n`);

const extensionSchemaPath = "schemas/HybridStudioExtension.schema.json";
const extensionSchema = JSON.parse(read(extensionSchemaPath));
extensionSchema.properties.permissions.items.enum = capabilityIds;
extensionSchema.properties.capabilityPolicy.properties.capabilities.items.enum = capabilityIds;
emit(extensionSchemaPath, `${JSON.stringify(extensionSchema, null, 2)}\n`);

const apiPolicy = JSON.parse(read("src/contracts/public-api-policy.json"));
const apiSource = read("src/runtime/parts/170-public-api.js");
const apiBlock = apiSource.match(/window\.HybridTileGraft\s*=\s*\{([\s\S]*?)\n\s*\};/)?.[1];
if (!apiBlock) throw new Error("Could not find the HybridTileGraft public API object.");
const apiNames = apiBlock.split(/\r?\n/).map(line => line.match(/^\s{8}([A-Za-z_$][\w$]*)(?=\s*[:,(])/)?.[1]).filter(Boolean);
if (new Set(apiNames).size !== apiNames.length) throw new Error("HybridTileGraft public API names must be unique.");
const compatibilityPattern = new RegExp(apiPolicy.compatibilityNamePattern);
const experimental = new Set(apiPolicy.experimental || []);
const deprecated = apiPolicy.deprecated || {};
const apiEntries = apiNames.map(name => ({
  name,
  kind: ["version", "pluginName"].includes(name) ? "property" : "function",
  stability: deprecated[name] ? "deprecated" : experimental.has(name) ? "experimental" : compatibilityPattern.test(name) ? "compatibility" : apiPolicy.defaultStability,
  ...(deprecated[name] ? { deprecated: deprecated[name] } : {})
}));
const apiManifest = {
  format: "HybridTileGraftPublicApiManifest",
  version: 1,
  pluginVersion: manifest.version,
  apiVersion: apiPolicy.apiVersion,
  removalPolicy: apiPolicy.removalPolicy,
  entries: apiEntries
};
emit("HybridTileGraft.api.json", `${JSON.stringify(apiManifest, null, 2)}\n`);
const declarations = apiEntries.map(item => item.kind === "property"
  ? `  readonly ${item.name}: string;`
  : `  readonly ${item.name}: HybridTileGraftFunction;`).join("\n");
emit("HybridTileGraft.d.ts", `/* Generated by scripts/build-release.js — public API names and stability live in HybridTileGraft.api.json. */\n` +
  `export type HybridTileGraftFunction = (...args: unknown[]) => unknown;\n\n` +
  `export interface HybridTileGraftApi {\n${declarations}\n}\n\n` +
  `declare global {\n  interface Window { HybridTileGraft: HybridTileGraftApi; }\n  var HybridTileGraft: HybridTileGraftApi;\n}\n\nexport {};\n`);
const stabilityCounts = Object.fromEntries(["stable", "compatibility", "experimental", "deprecated"].map(value => [value, apiEntries.filter(item => item.stability === value).length]));
emit("PUBLIC_API.md", `# HybridTileGraft public API contract\n\n` +
  `The generated \`HybridTileGraft.api.json\` inventory contains ${apiEntries.length} public entries: ${stabilityCounts.stable} stable, ${stabilityCounts.compatibility} compatibility, ${stabilityCounts.experimental} experimental, and ${stabilityCounts.deprecated} deprecated. \`HybridTileGraft.d.ts\` exposes the same names to JavaScript-aware editors.\n\n` +
  `## Stability policy\n\n${apiPolicy.removalPolicy}\n\n` +
  `The contract test rejects missing, duplicate, or unclassified exports. Detailed argument and return shapes continue to be documented in the plugin help and format schemas; declarations intentionally use \`unknown\` until an API receives a narrower reviewed signature.\n`);

const engineMatrix = JSON.parse(read("tests/fixtures/rpgmaker/engine-matrix.json"));
const engineRows = engineMatrix.engines.map(item => `| ${item.version} | ${item.role} | ${item.coreSource} | \`${item.marker}\` |`).join("\n");
emit("ENGINE_COMPATIBILITY.md", `# RPG Maker MZ engine compatibility\n\n` +
  `Supported range: **${engineMatrix.supportedRange}**. This file is generated from \`tests/fixtures/rpgmaker/engine-matrix.json\`.\n\n` +
  `| Engine | Role | Source | Retained evidence |\n|---|---|---|---|\n${engineRows}\n\n` +
  `Each marker must come from the official editor or an official bundled corescript, use the exact generated \`HybridTileGraft.js\` and smoke probe, complete a real save/reset/load cycle, record save size and frame timing, and clean its temporary save. Run \`npm run test:rpgmaker-evidence\` to reject stale evidence.\n`);

// The RPG Maker deliverable remains one plugin file, assembled from named source parts.
const plugin = manifest.runtime.parts.map(expected).join("");
emit(manifest.runtime.output, plugin);

// Active shell and desktop adapters are authored under src/ and copied to release roots.
for (const name of manifest.studioFiles) emit(name, read(path.posix.join("src/studio", name)));
for (const name of manifest.desktopFiles) emit(name, read(path.posix.join("src/desktop", name)));

// Embed schemas so file:// desktop builds and offline sessions execute the same contracts.
const schemas = {};
for (const relative of filesUnder("schemas").filter(name => name.endsWith(".json")).sort()) {
  schemas[path.basename(relative)] = JSON.parse(expected(relative));
}
emit("HybridTileSchemasV18.js", `/* Generated by scripts/build-release.js — executable schema registry */\nglobalThis.HybridTileSchemaDocumentsV18 = Object.freeze(${JSON.stringify(schemas)});\n`);

const explicit = [
  manifest.runtime.output,
  ...manifest.studioFiles,
  ...manifest.desktopFiles,
  "HybridTileSchemasV18.js", "HybridTileGraft.api.json", "HybridTileGraft.d.ts", "EXTENSION_CAPABILITIES.md", "PUBLIC_API.md", "ENGINE_COMPATIBILITY.md",
  "service-worker.js", "manifest.webmanifest", "package.json", "package.nw.json"
];
const legacy = manifest.legacyWorkbenchVersions.flatMap(version => [
  `HybridTileStudioV${version}.js`, ...(version >= 10 ? [`HybridTileStudioV${version}.css`] : [])
]);
const candidates = [...new Set([...explicit, ...legacy, ...filesUnder("schemas"), ...filesUnder("examples"), ...filesUnder("extensions")])]
  .filter(relative => fs.existsSync(path.join(ROOT, relative)) && fs.statSync(path.join(ROOT, relative)).isFile())
  .sort();
const assetManifest = {
  format: "HybridTileAssetManifest",
  version: 1,
  appVersion: manifest.version,
  core: manifest.coreAssets,
  assets: Object.fromEntries(candidates.map(relative => [relative, digest(relative)]))
};
emit("asset-manifest.json", `${JSON.stringify(assetManifest, null, 2)}\n`);

if (CHECK && changes.length) {
  console.error(`Generated files are stale: ${changes.join(", ")}`);
  process.exit(1);
}
console.log(changes.length ? `${CHECK ? "Would update" : "Updated"}: ${changes.join(", ")}` : "Generated files are current.");
