#!/usr/bin/env node
"use strict";
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.resolve(__dirname, "..");
const CHECK = process.argv.includes("--check");
const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, "src/manifest.json"), "utf8"));
const changes = [];

function read(relative) { return fs.readFileSync(path.join(ROOT, relative), "utf8"); }
function emit(relative, content) {
  const target = path.join(ROOT, relative);
  const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;
  if (current === content) return;
  changes.push(relative);
  if (!CHECK) { fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, content); }
}
function filesUnder(relative) {
  const base = path.join(ROOT, relative);
  if (!fs.existsSync(base)) return [];
  const output = [];
  for (const entry of fs.readdirSync(base, { withFileTypes: true })) {
    const child = path.posix.join(relative.replace(/\\/g,"/"), entry.name);
    if (entry.isDirectory()) output.push(...filesUnder(child)); else output.push(child);
  }
  return output;
}
function digest(relative) {
  const bytes = fs.readFileSync(path.join(ROOT, relative));
  return { sha256: crypto.createHash("sha256").update(bytes).digest("hex"), bytes: bytes.length };
}

// The RPG Maker deliverable remains one plugin file, assembled from named source parts.
const plugin = manifest.runtime.parts.map(read).join("");
emit(manifest.runtime.output, plugin);

// Active shell and desktop adapters are authored under src/ and copied to release roots.
for (const name of manifest.studioFiles) emit(name, read(path.posix.join("src/studio", name)));
for (const name of manifest.desktopFiles) emit(name, read(path.posix.join("src/desktop", name)));

// Embed schemas so file:// desktop builds and offline sessions execute the same contracts.
const schemas = {};
for (const relative of filesUnder("schemas").filter(name => name.endsWith(".json")).sort()) {
  schemas[path.basename(relative)] = JSON.parse(read(relative));
}
emit("HybridTileSchemasV18.js", `/* Generated by scripts/build-release.js — executable schema registry */\nglobalThis.HybridTileSchemaDocumentsV18 = Object.freeze(${JSON.stringify(schemas)});\n`);

const explicit = [
  manifest.runtime.output,
  ...manifest.studioFiles,
  ...manifest.desktopFiles,
  "HybridTileSchemasV18.js", "service-worker.js", "manifest.webmanifest", "package.json", "package.nw.json"
];
const legacy = manifest.legacyWorkbenchVersions.flatMap(version => [
  `HybridTileStudioV${version}.js`, ...(version >= 10 ? [`HybridTileStudioV${version}.css`] : [])
]);
const candidates = [...new Set([...explicit, ...legacy, ...filesUnder("schemas"), ...filesUnder("examples"), ...filesUnder("extensions")])]
  .filter(relative => fs.existsSync(path.join(ROOT, relative)) && fs.statSync(path.join(ROOT, relative)).isFile())
  .sort();
const assetManifest = {
  format: "HybridTileAssetManifest",
  version: 1,
  appVersion: manifest.version,
  core: manifest.coreAssets,
  assets: Object.fromEntries(candidates.map(relative => [relative, digest(relative)]))
};
emit("asset-manifest.json", `${JSON.stringify(assetManifest, null, 2)}\n`);

if (CHECK && changes.length) {
  console.error(`Generated files are stale: ${changes.join(", ")}`);
  process.exit(1);
}
console.log(changes.length ? `${CHECK ? "Would update" : "Updated"}: ${changes.join(", ")}` : "Generated files are current.");
